stages:
  - build

variables:
  RELEASE_REPO: "http://nexus/nexus/content/repositories/gradle-releases"
  SNAPSHOT_REPO: "http://nexus/nexus/content/repositories/snapshots"

build_job:
  script:
    - export JAVA_HOME=$JAVA7_HOME
    - export PATH=$JAVA_HOME/bin:$PATH
    # this is necessary for the build info
    - export CI_BUILD_TIMESTAMP=`date +'%Y%m%d%H%M%S'`
    - ./gradlew --no-daemon -PrunOnCI=true -s  -PreleaseRepo=$RELEASE_REPO -PsnapshotRepo=$SNAPSHOT_REPO -PdeployUserLogin=$REPOUSER -PdeployUserPassword=$REPOUSERPASSWD clean test jacocoTestReport
  stage: build
  except:
    - master
    - tags
  tags:
    - java7
  artifacts:
    paths:
    - build/reports/

publish_job:
  script:
    - export JAVA_HOME=$JAVA7_HOME
    - export PATH=$JAVA_HOME/bin:$PATH
    - ./gradlew --no-daemon -PrunOnCI=true -s -PreleaseRepo=$RELEASE_REPO -PsnapshotRepo=$SNAPSHOT_REPO -PdeployUserLogin=$REPOUSER -PdeployUserPassword=$REPOUSERPASSWD clean test jacocoTestReport publish
  stage: build
  only:
    - master
    - tags
  tags:
    - java7
  artifacts:
    paths:
    - build/reports/